name: Executar Testes Robot Framework

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependências do Python
        run: pip install -r requirements.txt
      
      # REMOVEMOS O PASSO DE INSTALAÇÃO MANUAL DO NAVEGADOR E DRIVER

      - name: Executar testes com servidor web
        run: |
          # Inicia o servidor web em background
          python3 -m http.server 8000 &
          
          # Espera um pouco para o servidor iniciar
          sleep 3
          
          # Executa os testes. A SeleniumLibrary vai baixar o driver correto automaticamente.
          # O alias 'headlesschrome' já configura o navegador para rodar em modo invisível.
          robot --variable BROWSER:headlesschrome --outputdir tests/results tests/

      - name: Fazer upload dos relatórios de teste
        if: always() # Sempre executa este passo, mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-robot
          path: |
            tests/results/log.html
            tests/results/report.html
            tests/results/output.xml